# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with Unittest
      env:
        SECRET_KEY : ${{ secret.SECRET_key }}
        DB_ENGINE : ${{ secret.DB_ENGINE }}
        DB_NAME : ${{ secret.DB_NAME }}
        DB_USER : ${{ secret.DB_USER }}
        DB_PASSWORD : ${{ secret.DB_PASSWORD }}
        DB_PORT : ${{ secret.DB_PORT }}
        DB_HOST : ${{ secret.DB_HOST }}
      run: |
        python manage.py test 
